apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImNISmhZM1JwWTNWdGMzUjFaR1Z1ZERJd01qVTZaMmh3WDJodlVWcDBVMHhJUXpSeFJFOTBRVE5VVjJ0WlFWWlRTMVJWZFVOUlZUQlBhM2hxWkE9PSIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJjdXJyZW50Q29udGV4dCI6ICJjb2xpbWEiCn0K
type: kubernetes.io/dockerconfigjson
